"""empty message

Revision ID: 27006728571c
Revises: b35c72d8d85f
Create Date: 2022-01-16 17:17:14.817368

"""

# revision identifiers, used by Alembic.
revision = '27006728571c'
down_revision = 'b35c72d8d85f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
