"""empty message

Revision ID: abcaeda711f9
Revises: b1fc06bece22
Create Date: 2022-01-17 15:48:03.404712

"""

# revision identifiers, used by Alembic.
import json

import requests
from elasticsearch import helpers
from sqlalchemy import MetaData, Table

import config
from models import ES

revision = 'abcaeda711f9'
down_revision = 'b1fc06bece22'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    data = json.loads(requests.get('https://api.jsonbin.io/b/61e47db70f639830851d4bfe').content)
    meta = MetaData(bind=op.get_bind())
    meta.reflect(only=('movies',))
    movies_table = Table('movies', meta)
    genres_table = Table('genres', meta)
    op.bulk_insert(movies_table, [{"name": movie['name'],  "director": movie['director'], "imdb_score": movie['imdb_score'], "popularity": movie['popularity'], "genre": [genre.id for genre in genres_table.select().where(genres_table.name == movie['genre']).execute().fetchall()]} for movie in data])

    actions = [
        {
            "_index": config.ES_INDEX,
            "_type": config.ES_DOC_TYPE,
            "_id": j+1,
            "_source": {
                "name": data[j]['name'],
                "director": data[j]['director'],
                "imdb_score": data[j]['imdb_score'],
                "popularity": data[j]['popularity'],
                "genre": data[j]['genre']
                }
        }
        for j in range(0, len(data))
    ]

    helpers.bulk(ES, actions)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
