"""empty message

Revision ID: b1fc06bece22
Revises: 933494d2de11
Create Date: 2022-01-16 17:54:39.988595

"""

# revision identifiers, used by Alembic.

import requests
from sqlalchemy import MetaData, Table

revision = 'b1fc06bece22'
down_revision = '933494d2de11'

from alembic import op
import sqlalchemy as sa
import json
from src.models import Genres


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    data = json.loads(requests.get('https://api.jsonbin.io/b/61e47db70f639830851d4bfe').content)
    genres = set()
    for movie in data:
        genres.update(movie['genre'])

    meta = MetaData(bind=op.get_bind())
    meta.reflect(only=('genres',))
    genres_table = Table('genres', meta)
    print(genres)
    op.bulk_insert(genres_table, [{'title': genre} for genre in genres])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
